version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: edu-management-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: edu-management
    volumes:
      - mongodb_data:/data/db
    networks:
      - edu-network

  mongo-express:
    image: mongo-express:latest
    container_name: edu-management-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - edu-network

volumes:
  mongodb_data:

networks:
  edu-network:
    driver: bridge